### ISSUE TITLE
[waiting / blocked until 2023] Remove Debug-Mode Testrun Main-Push

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1719]
In https://github.com/e-valuation/EvaP/pull/1257 we introduced that CI [also runs the tests in debug mode](https://github.com/e-valuation/EvaP/pull/1257/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R15).

During debug execution, it seems that django does lots of additional work, e.g. it [keeps a log of all database queries around](https://docs.djangoproject.com/en/3.2/faq/models/#how-can-i-see-the-raw-sql-queries-django-is-running), which occupies loads of ram. For running the tests with debug=true in the VM, you need around 4,5GB of memory available. With the default VM configuration, it will simply fail. Test execution is around 3 times slower, on CI, a non-debug run takes 1:45 where a debug run takes 5:49.

[The django feature ticket for running the tests in debug mode](https://code.djangoproject.com/ticket/27008) says that this flag is intended to troubleshoot test failures.

So far, I know of one instance where reportedly non-debug tests passed and debug tests would have given an error, because we messed up some variables in a template: https://github.com/e-valuation/EvaP/issues/868. However, this was in 2016, many django versions ago. From the current django documentation, I'd say it shouldn't make a difference for template errors whether debug is enabled. The only situation where a test failure depends on DEBUG that I can think of is in our own code, if we depend on DEBUG.

Pro:
- Reduce energy consumed on every single CI run, and CI runs will finish faster (2 minutes rather than 6 minutes)

Con:
- We will not test code paths of ours that explicitly branch on `settings.DEBUG` anymore. We currently have this 3 times, and its always a re-raise for debugging. We will not lose any coverage on codecov, because the debug runs are not measured for coverage currently.
    - Theoretically, this might create situations where a test will succeed but a `DEBUG=True` instance will show an error. I'd say that this is unlikely enough that we should do it and benefit from the shorter CI run time. If it happens, we will notice.
    - We can still annotate tests with a settings override to have them run with `DEBUG=True` if we want to test code that relies on this flag. (We currently have 2 tests that force `DEBUG=False` to prevent the re-raise mentioned above)

I looked at the CI output for these django projects and at seems like none of them executes test with debug-mode enabled on CI: [wagtail](https://github.com/wagtail/wagtail), [PostHog](https://github.com/PostHog/posthog), [Cabot](https://github.com/arachnys/cabot), [django-oscar](https://github.com/django-oscar/django-oscar), [mezzanine](https://github.com/stephenmcd/mezzanine), [edx-platform](https://github.com/openedx/edx-platform), [taiga-back](https://github.com/kaleidos-ventures/taiga-back/), [djangoproject.com](https://github.com/django/djangoproject.com).

I'd vote for removing the debug run, for the environment (and because I hate waiting for computers). What do you think?

**Comment by niklasmohrin** [comment]
I agree with removing the debug run from PRs. We could keep it as a step for the run that is triggered when commits are pushed to main - this way we would be certain that we dont miss any failures in the long term. You still make a good point for removing it altogether - I am fine with either way

**Comment by He3lixxx** [comment]
We agreed on removing the tests from PR runs for now, but keep them enabled for main. We expect them to never fail unless the non-debug runs fail. If this matches what we observe in the next year, we will consider removing it from main, too. This issue will remain open in the meantime.

**Comment by niklasmohrin** [comment]
3 years later, we have 15 failures and 2 errors on main haha

```plain
ERROR: test_passworduser_login (evap.evaluation.tests.test_auth.LoginTests.test_passworduser_login)
Tests whether a user can login with an incorrect and a correct password.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/bm7mwi7d03v3ynzy9w74jqcidrnmj0bi-evap-dev-env/lib/python3.13/site-packages/django/test/utils.py", line 458, in inner
    return func(*args, **kwargs)
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/test_auth.py", line 249, in test_passworduser_login
    self.assertIsInstance(response.context["user"], AnonymousUser)
                          ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/nix/store/bm7mwi7d03v3ynzy9w74jqcidrnmj0bi-evap-dev-env/lib/python3.13/site-packages/django/template/context.py", line 91, in __getitem__
    raise KeyError(key)
KeyError: 'user'

======================================================================
ERROR: test_evaluation_ended (evap.evaluation.tests.test_models.TestEvaluations.test_evaluation_ended)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/test_models.py", line 252, in test_evaluation_ended
    Evaluation.update_evaluations()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/models.py", line 1096, in update_evaluations
    evaluation.end_review()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/bm7mwi7d03v3ynzy9w74jqcidrnmj0bi-evap-dev-env/lib/python3.13/site-packages/django_fsm/__init__.py", line 688, in _change_state
    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/bm7mwi7d03v3ynzy9w74jqcidrnmj0bi-evap-dev-env/lib/python3.13/site-packages/django_fsm/__init__.py", line 371, in change_state
    raise TransitionNotAllowed(
    ...<3 lines>...
    )
django_fsm.TransitionNotAllowed: Can't switch from state '50' using method 'end_review'

======================================================================
FAIL: test_import_contributor_contribution_update (evap.cms.tests.test_json_importer.TestImportEvents.test_import_contributor_contribution_update)
Regression test for #2728
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 448, in test_import_contributor_contribution_update
    self._import(assert_nop=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 326, in _import
    with cm:
         ^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!hsxiNtX7ZpIbUVpYCKZhHEApiMrkDSfurstBX39T', NULL, '1@example.com', '', '1', '', '1', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_import_courses (evap.cms.tests.test_json_importer.TestImportEvents.test_import_courses)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/bm7mwi7d03v3ynzy9w74jqcidrnmj0bi-evap-dev-env/lib/python3.13/site-packages/django/test/utils.py", line 458, in inner
    return func(*args, **kwargs)
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 334, in test_import_courses
    self._import(assert_nop=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 326, in _import
    with cm:
         ^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!oNshw2220w8C7PWqEo6SxaaT5O7jdrppAt6kdPiq', NULL, '1@example.com', '', '1', '', '1', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_import_courses_evaluation_approved (evap.cms.tests.test_json_importer.TestImportEvents.test_import_courses_evaluation_approved)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 710, in test_import_courses_evaluation_approved
    importer = self._import(assert_nop=True)
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 326, in _import
    with cm:
         ^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!rOVCtRQZycciaFSOujHfF8ChHu3MCekUK1T9I4O1', NULL, '1@example.com', '', '1', '', '1', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_import_courses_evaluation_running (evap.cms.tests.test_json_importer.TestImportEvents.test_import_courses_evaluation_running)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 739, in test_import_courses_evaluation_running
    importer = self._import(assert_nop=True)
  File "/home/niklas/Dev/EvaP/evap/cms/tests/test_json_importer.py", line 326, in _import
    with cm:
         ^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!q3qrUTbiVik5wHOek5MT2ym3hlkH9QQCE8azm8K8', NULL, '1@example.com', '', '1', '', '1', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_no_empty_m2m_logs (evap.evaluation.tests.test_models_logging.TestLoggedModel.test_no_empty_m2m_logs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/test_models_logging.py", line 215, in test_no_empty_m2m_logs
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_semester" ("name_de", "name_en", "short_name_de", "short_name_en", "cms_name", "default_course_end_date", "participations_are_archived", "grade_documents_are_deleted", "results_are_archived", "created_at", "is_active") VALUES ('PaVqnzsrKTgVxSpnCfyM', 'ndMjSVQFBUeAchgJLePd', 'TxmzSVoyLKWymBTXtRbx', 'DaMKIvIvDfvJAIvxbXlp', '', NULL, false, false, false, '2026-08-04'::date, NULL) RETURNING "evaluation_semester"."id"

======================================================================
FAIL: test_duplicate_course_error (evap.staff.tests.test_importers.TestEnrollmentImport.test_duplicate_course_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_importers.py", line 595, in test_duplicate_course_error
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_semester" ("name_de", "name_en", "short_name_de", "short_name_en", "cms_name", "default_course_end_date", "participations_are_archived", "grade_documents_are_deleted", "results_are_archived", "created_at", "is_active") VALUES ('PaVqnzsrKTgVxSpnCfyM', 'ndMjSVQFBUeAchgJLePd', 'TxmzSVoyLKWymBTXtRbx', 'DaMKIvIvDfvJAIvxbXlp', '', NULL, false, false, false, '2026-08-04'::date, NULL) RETURNING "evaluation_semester"."id"

======================================================================
FAIL: test_existing_course_different_attributes (evap.staff.tests.test_importers.TestEnrollmentImport.test_existing_course_different_attributes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_importers.py", line 712, in test_existing_course_different_attributes
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!txKwDI3Qpp60bUaIrAhvPb6QkZLN5QldxF3rQrL6', NULL, '123@institution.example.com', 'Prof. Dr.', 'Christoph', '', 'Prorsus', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_existing_course_different_grading (evap.staff.tests.test_importers.TestEnrollmentImport.test_existing_course_different_grading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_importers.py", line 786, in test_existing_course_different_grading
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!jGNKt9i0Ias1pjjDbR7OkyLkIN9EQTXLzcPQL4Le', NULL, '123@institution.example.com', 'Prof. Dr.', 'Christoph', '', 'Prorsus', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_existing_course_equal_except_evaluations (evap.staff.tests.test_importers.TestEnrollmentImport.test_existing_course_equal_except_evaluations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_importers.py", line 767, in test_existing_course_equal_except_evaluations
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!JR1nafTtzy7i0GNWW0Xoj2ZQLmwYqknURLY1koMP', NULL, '123@institution.example.com', 'Prof. Dr.', 'Christoph', '', 'Prorsus', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_existing_course_with_published_evaluation (evap.staff.tests.test_importers.TestEnrollmentImport.test_existing_course_with_published_evaluation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_importers.py", line 733, in test_existing_course_with_published_evaluation
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_userprofile" ("is_superuser", "password", "last_login", "email", "title", "first_name_given", "first_name_chosen", "last_name", "language", "is_proxy_user", "login_key", "login_key_valid_until", "is_active", "notes", "startpage") VALUES (false, '!gGvnq67YPYQ9uVcKu0Kj8qTMQsHu2wECN6nnoYpA', NULL, '123@institution.example.com', 'Prof. Dr.', 'Christoph', '', 'Prorsus', '', false, NULL, NULL, true, '', 'DE') RETURNING "evaluation_userprofile"."id"

======================================================================
FAIL: test_imported_contributors_are_made_active (evap.staff.tests.test_importers.TestPersonImport.test_imported_contributors_are_made_active)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_importers.py", line 1040, in test_imported_contributors_are_made_active
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: UPDATE "evaluation_userprofile" SET "is_superuser" = false, "password" = '!4W0GlToSOklSlhArDW5q6Rt774pAJg08l7phg2iI', "last_login" = NULL, "email" = NULL, "title" = '', "first_name_given" = '', "first_name_chosen" = '', "last_name" = '', "language" = '', "is_proxy_user" = false, "login_key" = NULL, "login_key_valid_until" = NULL, "is_active" = false, "notes" = '', "startpage" = 'DE' WHERE "evaluation_userprofile"."id" = 286

======================================================================
FAIL: test_imported_participants_are_made_active (evap.staff.tests.test_importers.TestPersonImport.test_imported_participants_are_made_active)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_importers.py", line 1025, in test_imported_participants_are_made_active
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: UPDATE "evaluation_userprofile" SET "is_superuser" = false, "password" = '!ZANkMxKMRw7zZUE5fHDpD8yLuYN6DfFLKoJUvt0E', "last_login" = NULL, "email" = 'participant2@example.com', "title" = '', "first_name_given" = '', "first_name_chosen" = '', "last_name" = '', "language" = '', "is_proxy_user" = false, "login_key" = NULL, "login_key_valid_until" = NULL, "is_active" = false, "notes" = '', "startpage" = 'DE' WHERE "evaluation_userprofile"."id" = 285

======================================================================
FAIL: test_exam_evaluation_for_already_existing_exam_evaluation (evap.staff.tests.test_views.TestEvaluationExamCreation.test_exam_evaluation_for_already_existing_exam_evaluation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_views.py", line 2060, in test_exam_evaluation_for_already_existing_exam_evaluation
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: INSERT INTO "evaluation_examtype" ("name_de", "name_en", "import_names", "skip_on_automated_import", "order") VALUES ('PaVqnzsrKTgVxSpnCfyM', 'ndMjSVQFBUeAchgJLePd', '{}'::varchar(1024)[], false,  -1) RETURNING "evaluation_examtype"."id"

======================================================================
FAIL: test_exam_evaluation_with_wrong_date (evap.staff.tests.test_views.TestEvaluationExamCreation.test_exam_evaluation_with_wrong_date)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_views.py", line 2067, in test_exam_evaluation_with_wrong_date
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: UPDATE "evaluation_logentry" SET "content_type_id" = 9, "content_object_id" = 266, "attached_to_object_type_id" = 9, "attached_to_object_id" = 266, "datetime" = '2026-08-04 17:20:38.972054'::timestamp, "user_id" = NULL, "action_type" = 'create', "request_id" = '', "data" = '{"state": {"create": [10]}, "course": {"create": [269]}, "name_de": {"create": [""]}, "name_en": {"create": [""]}, "main_language": {"create": ["x"]}, "weight": {"create": [1]}, "is_rewarded": {"create": [true]}, "is_midterm_evaluation": {"create": [false]}, "vote_start_datetime": {"change": ["2026-06-15 17:20", "2026-11-12 17:20"]}, "vote_end_date": {"change": ["2026-08-04", "2027-01-01"]}, "allow_editors_to_edit": {"create": [true]}, "wait_for_grade_upload_before_publishing": {"create": [true]}, "staff_notes": {"create": [""]}, "participants": {"add": [369, 370, 371]}}'::jsonb WHERE "evaluation_logentry"."id" = 2289

======================================================================
FAIL: test_invalid_question_edit (evap.staff.tests.test_views.TestQuestionnaireEditView.test_invalid_question_edit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niklas/Dev/EvaP/evap/staff/tests/test_views.py", line 3404, in test_invalid_question_edit
    with assert_no_database_modifications():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/nix/store/l9k0anq0z7zz81zcwy035jfwap9ga6rl-python3-3.13.13/lib/python3.13/contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "/home/niklas/Dev/EvaP/evap/evaluation/tests/tools.py", line 334, in assert_no_database_modifications
    raise AssertionError("Unexpected modifying query found: " + query["sql"])
AssertionError: Unexpected modifying query found: UPDATE "evaluation_userprofile" SET "is_superuser" = false, "password" = '!EtlUXs5jV292ijP2Vx9pjDDqj5G712Htzm24nlHM', "last_login" = '2026-08-04 17:22:03.168895'::timestamp, "email" = 'manager@institution.example.com', "title" = '', "first_name_given" = '', "first_name_chosen" = '', "last_name" = '', "language" = 'en', "is_proxy_user" = false, "login_key" = NULL, "login_key_valid_until" = NULL, "is_active" = true, "notes" = '', "startpage" = 'DE' WHERE "evaluation_userprofile"."id" = 603

----------------------------------------------------------------------
Ran 671 tests in 251.252s

FAILED (failures=15, errors=2)
```

**Comment by richardebeling** [comment]
Wait why does the `assert_no_database_modifications()` not fire if not in debug mode?

**Comment by niklasmohrin** [comment]
I have no idea 😄

**Comment by Kakadus** [comment]
regarding the first error, it's just that `response.context` is not populated on the technical error debug page, and there is no easy way around this (Django deliberately uses a stripped down renderer for this page). Also, Django 6.0 broke assertContains on those responses because it no longer returns a charset there.

**Comment by Kakadus** [comment]
bisected the second issue to 61d5ca588c48b9349de44c2931601dd8be8cf4c6, which makes sense that this changes behavior in debug mode.
https://github.com/e-valuation/EvaP/blob/61d5ca588c48b9349de44c2931601dd8be8cf4c6/evap/evaluation/models.py#L961-L963

**Comment by Kakadus** [comment]
as to the other errors, assert_no_database_modifications errors on db hits before the context manager: A simple
```py
        baker.make(UserProfile) 
        with assert_no_database_modifications():
            pass
```
fails already in debug mode. There is `CaptureQueriesContext.captured_queries` which indexes the entire query log correctly.

**Comment by niklasmohrin** [comment]
Nice work, thanks!
