### ISSUE TITLE
Sorting UserProfiles fails for incomplete names

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1797]
In several places UserProfiles are sorted by name. If first and/or last name are `None`, this currently fails with server errors in multiple views, e.g.:

`AttributeError at /staff/semester/[...]/grade_reminder 'NoneType' object has no attribute 'lower'`
```
Traceback (most recent call last):
  File "/opt/evap/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/evap/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/evap/evap/evaluation/auth.py", line 59, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/evap/evap/staff/views.py", line 861, in semester_grade_reminder
    responsibles.sort(key=lambda responsible: (responsible.last_name.lower(), responsible.first_name.lower()))
  File "/opt/evap/evap/staff/views.py", line 861, in <lambda>
    responsibles.sort(key=lambda responsible: (responsible.last_name.lower(), responsible.first_name.lower()))
```

`TypeError at /student/vote/[...]
'<' not supported between instances of 'NoneType' and 'str'
`
```
Traceback (most recent call last):
  File "/opt/evap/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/evap/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/evap/evap/evaluation/auth.py", line 59, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/evap/evap/student/views.py", line 188, in vote
    form_groups, rendered_page = get_valid_form_groups_or_render_vote_page(request, evaluation, preview=False)
  File "/opt/evap/evap/student/views.py", line 175, in get_valid_form_groups_or_render_vote_page
    general_contribution_textanswers_visible_to=textanswers_visible_to(evaluation.general_contribution),
  File "/opt/evap/evap/results/tools.py", line 454, in textanswers_visible_to
    sorted_contributors = sorted(contributors, key=lambda user: (user.last_name, user.first_name))
```

Sorting UserProfiles should also be possible when values are missing (e.g., an empty string could be used instead").

**Comment by He3lixxx** [comment]
Related, maybe duplicate: https://github.com/e-valuation/EvaP/issues/1624?

In #1794, we plan to just use django's `Meta.ordering` to do the sorting at the database level. We should then be able to remove most/all python-logic to sort user profiles. The PR is currently blocked by a django bug, and thus waits for the django 4.1 update.

**Comment by janno42** [comment]
Okay, we have bug issues open for way too long if I don't remember opening an issue about them anymore :)
We should hurry with the 4.1 update then.

**Comment by janno42** [comment]
Okay, we have bug issues open for way too long if I don't remember opening an issue about them anymore :)
We should hurry with the 4.1 update then.
